version: "3.3"
services:
#  oracle_db1:
#    image: gvenzl/oracle-xe:21-slim
#    ports:
#      - "1521:1521"
#    environment:
#      ORACLE_PASSWORD: Test1Test
#      ORACLE_DATABASE: TESTDB
#      APP_USER: test_user
#      APP_USER_PASSWORD: Test1Test
  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_db
    networks:
      - elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:8.4.2
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    networks:
#      - elastic
#  logstash:
#    container_name: logstash
#    build:
#      context: ../.logstash
#      dockerfile: dockerfile
#    networks:
#      - elastic
#    volumes:
#      - logstash-logs:/usr/share/logstash
#    depends_on:
#      - elasticsearch
#      - db

volumes:
  logstash-logs:
  database-data:
  elasticsearch-data:
    driver: local
networks:
  elastic:
    driver: bridge
