insert into countries(id, name_en, name_ar) values(1,'Afghanistan','أفغانستان');
insert into countries(id, name_en, name_ar) values(2,'Åland Islands','جزر أولاند');
insert into countries(id, name_en, name_ar) values(3,'Albania','ألبانيا');
insert into countries(id, name_en, name_ar) values(4,'Algeria','الجزائر');
insert into countries(id, name_en, name_ar) values(5,'American Samoa','ساموا الأمريكية');
insert into countries(id, name_en, name_ar) values(6,'Andorra','أندورا');
insert into countries(id, name_en, name_ar) values(7,'Angola','أنغولا');
insert into countries(id, name_en, name_ar) values(8,'Anguilla','أنغويلا');
insert into countries(id, name_en, name_ar) values(9,'Antarctica','القارة القطبية الجنوبية');
insert into countries(id, name_en, name_ar) values(10,'Antigua and Barbuda','أنتيغوا وبربودا');
insert into countries(id, name_en, name_ar) values(11,'Argentina','الأرجنتين');
insert into countries(id, name_en, name_ar) values(12,'Armenia','أرمينيا');
insert into countries(id, name_en, name_ar) values(13,'Aruba','أروبا');
insert into countries(id, name_en, name_ar) values(14,'Australia','أستراليا');
insert into countries(id, name_en, name_ar) values(15,'Austria','النمسا');
insert into countries(id, name_en, name_ar) values(16,'Azerbaijan','أذربيجان');
insert into countries(id, name_en, name_ar) values(17,'Bahamas','باهاماس');
insert into countries(id, name_en, name_ar) values(18,'Bahrain','البحرين');
insert into countries(id, name_en, name_ar) values(19,'Bangladesh','بنغلاديش');
insert into countries(id, name_en, name_ar) values(20,'Barbados','بربادوس');
insert into countries(id, name_en, name_ar) values(21,'Belarus','بيلاروسيا');
insert into countries(id, name_en, name_ar) values(22,'Belgium','بلجيكا');
insert into countries(id, name_en, name_ar) values(23,'Belize','بليز');
insert into countries(id, name_en, name_ar) values(24,'Benin','بنين');
insert into countries(id, name_en, name_ar) values(25,'Bermuda','برمودا');
insert into countries(id, name_en, name_ar) values(26,'Bhutan','بوتان');
insert into countries(id, name_en, name_ar) values(27,'Bolivia','بوليفيا');
insert into countries(id, name_en, name_ar) values(28,'Bosnia and Herzegovina','البوسنة والهرسك');
insert into countries(id, name_en, name_ar) values(29,'Botswana','بوتسوانا');
insert into countries(id, name_en, name_ar) values(30,'Bouvet Island','جزيرة بوفيه');
insert into countries(id, name_en, name_ar) values(31,'Brazil','البرازيل');
insert into countries(id, name_en, name_ar) values(32,'British Indian Ocean Territory','إقليم المحيط الهندي البريطاني');
insert into countries(id, name_en, name_ar) values(33,'British Virgin Islands','جزر العذراء البريطانية');
insert into countries(id, name_en, name_ar) values(34,'Brunei','بروناي');
insert into countries(id, name_en, name_ar) values(35,'Bulgaria','بلغاريا');
insert into countries(id, name_en, name_ar) values(36,'Burkina Faso','بوركينا فاسو');
insert into countries(id, name_en, name_ar) values(37,'Burundi','بوروندي');
insert into countries(id, name_en, name_ar) values(38,'Cabo Verde','كابو فيردي');
insert into countries(id, name_en, name_ar) values(39,'Cambodia','كمبوديا');
insert into countries(id, name_en, name_ar) values(40,'Cameroon','الكاميرون');
insert into countries(id, name_en, name_ar) values(41,'Canada','كندا');
insert into countries(id, name_en, name_ar) values(42,'Caribbean Netherlands','الجزر الكاريبية الهولندية');
insert into countries(id, name_en, name_ar) values(43,'Cayman Islands','جزر كايمان');
insert into countries(id, name_en, name_ar) values(44,'Central African Republic','جمهورية أفريقيا الوسطى');
insert into countries(id, name_en, name_ar) values(45,'Chad','تشاد');
insert into countries(id, name_en, name_ar) values(46,'Chile','تشيلي');
insert into countries(id, name_en, name_ar) values(47,'China','الصين');
insert into countries(id, name_en, name_ar) values(48,'Christmas Island','جزيرة الكريسماس');
insert into countries(id, name_en, name_ar) values(49,'Cocos (Keeling) Islands','جزر كوكوس');
insert into countries(id, name_en, name_ar) values(50,'Colombia','كولومبيا');
insert into countries(id, name_en, name_ar) values(51,'Comoros','جزر القمر');
insert into countries(id, name_en, name_ar) values(52,'Congo Republic','جمهورية الكونغو');
insert into countries(id, name_en, name_ar) values(53,'Cook Islands','جزر كوك');
insert into countries(id, name_en, name_ar) values(54,'Costa Rica','كوستاريكا');
insert into countries(id, name_en, name_ar) values(55,'Croatia','كرواتيا');
insert into countries(id, name_en, name_ar) values(56,'Cuba','كوبا');
insert into countries(id, name_en, name_ar) values(57,'Curaçao','كوراساو');
insert into countries(id, name_en, name_ar) values(58,'Cyprus','قبرص');
insert into countries(id, name_en, name_ar) values(59,'Czechia','التشيك');
insert into countries(id, name_en, name_ar) values(60,'Denmark','الدنمارك');
insert into countries(id, name_en, name_ar) values(61,'Djibouti','جيبوتي');
insert into countries(id, name_en, name_ar) values(62,'Dominica','دومينيكا');
insert into countries(id, name_en, name_ar) values(63,'Dominican Republic','جمهورية الدومينيكان');
insert into countries(id, name_en, name_ar) values(64,'DR Congo','جمهورية الكونغو الديمقراطية');
insert into countries(id, name_en, name_ar) values(65,'Ecuador','الاكوادور');
insert into countries(id, name_en, name_ar) values(66,'Egypt','مصر');
insert into countries(id, name_en, name_ar) values(67,'El Salvador','السلفادور');
insert into countries(id, name_en, name_ar) values(68,'Equatorial Guinea','غينيا الاستوائية');
insert into countries(id, name_en, name_ar) values(69,'Eritrea','إريتريا');
insert into countries(id, name_en, name_ar) values(70,'Estonia','إستونيا');
insert into countries(id, name_en, name_ar) values(71,'Eswatini','إسواتيني');
insert into countries(id, name_en, name_ar) values(72,'Ethiopia','إثيوبيا');
insert into countries(id, name_en, name_ar) values(73,'Falkland Islands','جزر فوكلاند');
insert into countries(id, name_en, name_ar) values(74,'Faroe Islands','جزر فارو');
insert into countries(id, name_en, name_ar) values(75,'Fiji','فيجي');
insert into countries(id, name_en, name_ar) values(76,'Finland','فنلندا');
insert into countries(id, name_en, name_ar) values(77,'France','فرنسا');
insert into countries(id, name_en, name_ar) values(78,'French Guiana','غويانا الفرنسية');
insert into countries(id, name_en, name_ar) values(79,'French Polynesia','بولينزيا الفرنسية');
insert into countries(id, name_en, name_ar) values(80,'French Southern Territories','أراض فرنسية جنوبية');
insert into countries(id, name_en, name_ar) values(81,'Gabon','الجابون');
insert into countries(id, name_en, name_ar) values(82,'Gambia','غامبيا');
insert into countries(id, name_en, name_ar) values(83,'Georgia','‫جورجيا');
insert into countries(id, name_en, name_ar) values(84,'Germany','ألمانيا');
insert into countries(id, name_en, name_ar) values(85,'Ghana','غانا');
insert into countries(id, name_en, name_ar) values(86,'Gibraltar','جبل طارق');
insert into countries(id, name_en, name_ar) values(87,'Greece','اليونان');
insert into countries(id, name_en, name_ar) values(88,'Greenland','جرينلاند');
insert into countries(id, name_en, name_ar) values(89,'Grenada','غرينادا');
insert into countries(id, name_en, name_ar) values(90,'Guadeloupe','غوادلوب');
insert into countries(id, name_en, name_ar) values(91,'Guam','غوام');
insert into countries(id, name_en, name_ar) values(92,'Guatemala','غواتيمالا');
insert into countries(id, name_en, name_ar) values(93,'Guernsey','غيرنزي');
insert into countries(id, name_en, name_ar) values(94,'Guinea','غينيا');
insert into countries(id, name_en, name_ar) values(95,'Guinea-Bissau','غينيا بيساو');
insert into countries(id, name_en, name_ar) values(96,'Guyana','غيانا');
insert into countries(id, name_en, name_ar) values(97,'Haiti','هايتي');
insert into countries(id, name_en, name_ar) values(98,'Heard Island and McDonald Islands','جزيرة هيرد وجزر ماكدونالد');
insert into countries(id, name_en, name_ar) values(99,'Honduras','هندوراس');
insert into countries(id, name_en, name_ar) values(100,'Hong Kong','هونج كونج');
insert into countries(id, name_en, name_ar) values(101,'Hungary','هنجاريا');
insert into countries(id, name_en, name_ar) values(102,'Iceland','آيسلندا');
insert into countries(id, name_en, name_ar) values(103,'India','الهند');
insert into countries(id, name_en, name_ar) values(104,'Indonesia','أندونيسيا');
insert into countries(id, name_en, name_ar) values(105,'Iran','إيران');
insert into countries(id, name_en, name_ar) values(106,'Iraq','العراق');
insert into countries(id, name_en, name_ar) values(107,'Ireland','أيرلندا');
insert into countries(id, name_en, name_ar) values(108,'Isle of Man','جزيرة مان');
insert into countries(id, name_en, name_ar) values(109,'Italy','إيطاليا');
insert into countries(id, name_en, name_ar) values(110,'Ivory Coast','ساحل العاج');
insert into countries(id, name_en, name_ar) values(111,'Jamaica','جامايكا');
insert into countries(id, name_en, name_ar) values(112,'Japan','اليابان');
insert into countries(id, name_en, name_ar) values(113,'Jersey','جيرسي');
insert into countries(id, name_en, name_ar) values(114,'Jordan','الأردن');
insert into countries(id, name_en, name_ar) values(115,'Kazakhstan','كازاخستان');
insert into countries(id, name_en, name_ar) values(116,'Kenya','كينيا');
insert into countries(id, name_en, name_ar) values(117,'Kiribati','كيريباتي');
insert into countries(id, name_en, name_ar) values(118,'Kosovo','كوسوفو');
insert into countries(id, name_en, name_ar) values(119,'Kuwait','الكويت');
insert into countries(id, name_en, name_ar) values(120,'Kyrgyzstan','قيرغيزستان');
insert into countries(id, name_en, name_ar) values(121,'Laos','لاوس');
insert into countries(id, name_en, name_ar) values(122,'Latvia','لاتفيا');
insert into countries(id, name_en, name_ar) values(123,'Lebanon','لبنان');
insert into countries(id, name_en, name_ar) values(124,'Lesotho','ليسوتو');
insert into countries(id, name_en, name_ar) values(125,'Liberia','ليبيريا');
insert into countries(id, name_en, name_ar) values(126,'Libya','ليبيا');
insert into countries(id, name_en, name_ar) values(127,'Liechtenstein','ليختنشتاين');
insert into countries(id, name_en, name_ar) values(128,'Lithuania','ليتوانيا');
insert into countries(id, name_en, name_ar) values(129,'Luxembourg','لوكسمبورغ');
insert into countries(id, name_en, name_ar) values(130,'Macao','ماكاو');
insert into countries(id, name_en, name_ar) values(131,'Madagascar','مدغشقر');
insert into countries(id, name_en, name_ar) values(132,'Malawi','مالاوي');
insert into countries(id, name_en, name_ar) values(133,'Malaysia','ماليزيا');
insert into countries(id, name_en, name_ar) values(134,'Maldives','المالديف');
insert into countries(id, name_en, name_ar) values(135,'Mali','مالي');
insert into countries(id, name_en, name_ar) values(136,'Malta','مالطا');
insert into countries(id, name_en, name_ar) values(137,'Marshall Islands','جزر مارشال');
insert into countries(id, name_en, name_ar) values(138,'Martinique','مارتينيك');
insert into countries(id, name_en, name_ar) values(139,'Mauritania','موريتانيا');
insert into countries(id, name_en, name_ar) values(140,'Mauritius','موريشيوس');
insert into countries(id, name_en, name_ar) values(141,'Mayotte','مايوت');
insert into countries(id, name_en, name_ar) values(142,'Mexico','المكسيك');
insert into countries(id, name_en, name_ar) values(143,'Micronesia','ولايات ميكرونيسيا المتحدة');
insert into countries(id, name_en, name_ar) values(144,'Moldova','مولدوفا');
insert into countries(id, name_en, name_ar) values(145,'Monaco','موناكو');
insert into countries(id, name_en, name_ar) values(146,'Mongolia','منغوليا');
insert into countries(id, name_en, name_ar) values(147,'Montenegro','مونتينيغرو');
insert into countries(id, name_en, name_ar) values(148,'Montserrat','مونتسرات');
insert into countries(id, name_en, name_ar) values(149,'Morocco','المغرب');
insert into countries(id, name_en, name_ar) values(150,'Mozambique','موزمبيق');
insert into countries(id, name_en, name_ar) values(151,'Myanmar','ميانمار');
insert into countries(id, name_en, name_ar) values(152,'Namibia','ناميبيا');
insert into countries(id, name_en, name_ar) values(153,'Nauru','ناورو');
insert into countries(id, name_en, name_ar) values(154,'Nepal','نيبال');
insert into countries(id, name_en, name_ar) values(155,'Netherlands','هولندا');
insert into countries(id, name_en, name_ar) values(156,'Netherlands Antilles','جزر الأنتيل الهولندية');
insert into countries(id, name_en, name_ar) values(157,'New Caledonia','كاليدونيا الجديدة');
insert into countries(id, name_en, name_ar) values(158,'New Zealand','نيوزيلندا');
insert into countries(id, name_en, name_ar) values(159,'Nicaragua','نيكاراغوا');
insert into countries(id, name_en, name_ar) values(160,'Niger','النيجر');
insert into countries(id, name_en, name_ar) values(161,'Nigeria','نيجيريا');
insert into countries(id, name_en, name_ar) values(162,'Niue','نييوي');
insert into countries(id, name_en, name_ar) values(163,'Norfolk Island','جزيرة نورفولك');
insert into countries(id, name_en, name_ar) values(164,'North Korea','كوريا الشمالية');
insert into countries(id, name_en, name_ar) values(165,'North Macedonia','مقدونيا الشمالية');
insert into countries(id, name_en, name_ar) values(166,'Northern Mariana Islands','جزر ماريانا الشمالية');
insert into countries(id, name_en, name_ar) values(167,'Norway','النرويج');
insert into countries(id, name_en, name_ar) values(168,'Oman','سلطنة عمان');
insert into countries(id, name_en, name_ar) values(169,'Pakistan','باكستان');
insert into countries(id, name_en, name_ar) values(170,'Palau','بالاو');
insert into countries(id, name_en, name_ar) values(171,'Palestine','فلسطين');
insert into countries(id, name_en, name_ar) values(172,'Panama','بنما');
insert into countries(id, name_en, name_ar) values(173,'Papua New Guinea','بابوا غينيا الجديدة');
insert into countries(id, name_en, name_ar) values(174,'Paraguay','باراغواي');
insert into countries(id, name_en, name_ar) values(175,'Peru','بيرو');
insert into countries(id, name_en, name_ar) values(176,'Philippines','الفلبين');
insert into countries(id, name_en, name_ar) values(177,'Pitcairn Islands','جزر بيتكيرن');
insert into countries(id, name_en, name_ar) values(178,'Poland','بولندا');
insert into countries(id, name_en, name_ar) values(179,'Portugal','البرتغال');
insert into countries(id, name_en, name_ar) values(180,'Puerto Rico','بورتوريكو');
insert into countries(id, name_en, name_ar) values(181,'Qatar','قطر');
insert into countries(id, name_en, name_ar) values(182,'Réunion','ريونيون');
insert into countries(id, name_en, name_ar) values(183,'Romania','رومانيا');
insert into countries(id, name_en, name_ar) values(184,'Russia','روسيا');
insert into countries(id, name_en, name_ar) values(185,'Rwanda','رواندا');
insert into countries(id, name_en, name_ar) values(186,'Saint Barthélemy','سان بارتيلمي');
insert into countries(id, name_en, name_ar) values(187,'Saint Helena','سانت هيلينا');
insert into countries(id, name_en, name_ar) values(188,'Saint Kitts and Nevis','سانت كيتس ونيفيس');
insert into countries(id, name_en, name_ar) values(189,'Saint Lucia','سانت لوسيا');
insert into countries(id, name_en, name_ar) values(190,'Saint Martin','سانت مارتن');
insert into countries(id, name_en, name_ar) values(191,'Saint Pierre and Miquelon','سان بيير وميكلون');
insert into countries(id, name_en, name_ar) values(192,'Saint Vincent and the Grenadines','سانت فينسنت والغرينادين');
insert into countries(id, name_en, name_ar) values(193,'Samoa','ساموا');
insert into countries(id, name_en, name_ar) values(194,'San Marino','سان مارينو');
insert into countries(id, name_en, name_ar) values(195,'São Tomé and Príncipe','ساو تومي وبرينسيب');
insert into countries(id, name_en, name_ar) values(196,'Saudi Arabia','السعودية');
insert into countries(id, name_en, name_ar) values(197,'Senegal','السنغال');
insert into countries(id, name_en, name_ar) values(198,'Serbia','صربيا');
insert into countries(id, name_en, name_ar) values(199,'Seychelles','سيشل');
insert into countries(id, name_en, name_ar) values(200,'Sierra Leone','سيراليون');
insert into countries(id, name_en, name_ar) values(201,'Singapore','سنغافورة');
insert into countries(id, name_en, name_ar) values(202,'Sint Maarten','سانت مارتن');
insert into countries(id, name_en, name_ar) values(203,'Slovakia','سلوفاكيا');
insert into countries(id, name_en, name_ar) values(204,'Slovenia','سلوفينيا');
insert into countries(id, name_en, name_ar) values(205,'Solomon Islands','جزر سليمان');
insert into countries(id, name_en, name_ar) values(206,'Somalia','الصومال');
insert into countries(id, name_en, name_ar) values(207,'South Africa','جنوب أفريقيا');
insert into countries(id, name_en, name_ar) values(208,'South Georgia and South Sandwich Islands','جورجيا الجنوبية وجزر ساندويتش الجنوبية');
insert into countries(id, name_en, name_ar) values(209,'South Korea','كوريا الجنوبية');
insert into countries(id, name_en, name_ar) values(210,'South Sudan','جنوب السودان');
insert into countries(id, name_en, name_ar) values(211,'Spain','إسبانيا');
insert into countries(id, name_en, name_ar) values(212,'Sri Lanka','سريلانكا');
insert into countries(id, name_en, name_ar) values(213,'Sudan','السودان');
insert into countries(id, name_en, name_ar) values(214,'Suriname','سورينام');
insert into countries(id, name_en, name_ar) values(215,'Svalbard and Jan Mayen','سفالبارد ويان ماين');
insert into countries(id, name_en, name_ar) values(216,'Sweden','السويد');
insert into countries(id, name_en, name_ar) values(217,'Switzerland','سويسرا');
insert into countries(id, name_en, name_ar) values(218,'Syria','سوريا');
insert into countries(id, name_en, name_ar) values(219,'Taiwan','تايوان');
insert into countries(id, name_en, name_ar) values(220,'Tajikistan','طاجيكستان');
insert into countries(id, name_en, name_ar) values(221,'Tanzania','تنزانيا');
insert into countries(id, name_en, name_ar) values(222,'Thailand','تايلاند');
insert into countries(id, name_en, name_ar) values(223,'Timor-Leste','تيمور الشرقية');
insert into countries(id, name_en, name_ar) values(224,'Togo','توجو');
insert into countries(id, name_en, name_ar) values(225,'Tokelau','توكيلاو');
insert into countries(id, name_en, name_ar) values(226,'Tonga','تونغا');
insert into countries(id, name_en, name_ar) values(227,'Trinidad and Tobago','ترينيداد وتوباغو');
insert into countries(id, name_en, name_ar) values(228,'Tunisia','تونس');
insert into countries(id, name_en, name_ar) values(229,'Turkey','تركيا');
insert into countries(id, name_en, name_ar) values(230,'Turkmenistan','تركمانستان');
insert into countries(id, name_en, name_ar) values(231,'Turks and Caicos Islands','جزر توركس وكايكوس');
insert into countries(id, name_en, name_ar) values(232,'Tuvalu','توفالو');
insert into countries(id, name_en, name_ar) values(233,'U.S. Minor Outlying Islands','جزر الولايات المتحدة الصغيرة النائية');
insert into countries(id, name_en, name_ar) values(234,'U.S. Virgin Islands','جزر العذراء الأمريكية');
insert into countries(id, name_en, name_ar) values(235,'Uganda','أوغندا');
insert into countries(id, name_en, name_ar) values(236,'Ukraine','أوكرانيا');
insert into countries(id, name_en, name_ar) values(237,'United Arab Emirates','الإمارات العربية المتحدة');
insert into countries(id, name_en, name_ar) values(238,'United Kingdom','المملكة المتحدة');
insert into countries(id, name_en, name_ar) values(239,'United States of America','الولايات المتحدة الأمريكية');
insert into countries(id, name_en, name_ar) values(240,'Uruguay','أوروغواي');
insert into countries(id, name_en, name_ar) values(241,'Uzbekistan','أوزبكستان');
insert into countries(id, name_en, name_ar) values(242,'Vanuatu','فانواتو');
insert into countries(id, name_en, name_ar) values(243,'Vatican City','مدينة الفاتيكان');
insert into countries(id, name_en, name_ar) values(244,'Venezuela','فنزويلا');
insert into countries(id, name_en, name_ar) values(245,'Vietnam','فيتنام');
insert into countries(id, name_en, name_ar) values(246,'Wallis and Futuna','واليس وفوتونا');
insert into countries(id, name_en, name_ar) values(247,'Western Sahara','الصحراء الغربية');
insert into countries(id, name_en, name_ar) values(248,'Yemen','اليمن');
insert into countries(id, name_en, name_ar) values(249,'Zambia','زامبيا');
insert into countries(id, name_en, name_ar) values(250,'Zimbabwe','زيمبابوي');
