create table COUNTRIES (
	ID int primary key,
	NAME_EN VARCHAR(100) NOT NULL,
	NAME_AR VARCHAR(100) NOT NULL
);

CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	NAME_EN VARCHAR(100) NOT NULL,
	NAME_AR VARCHAR(100) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GENDER VARCHAR(6) NOT NULL,
	FAVOURITE_NUMBER INT NOT NULL,
	PLACE_OF_BIRTH INT NOT NULL,
	FOREIGN KEY (PLACE_OF_BIRTH)
      REFERENCES COUNTRIES (ID)
);